//
//  RenderedArtworkMetrics+Generated.swift
//  Inkwell Keeper
//
//  Generated by Scripts/storage_art/install_assets.py from the Blender renders.
//  Do not edit by hand — re-run the render and install scripts instead.
//

import SwiftUI

extension RenderedArtworkMetrics {
    static let binder = RenderedArtworkMetrics(
        prefix: "binder",
        bottomY: 0.9575
    )
    static let trove = RenderedArtworkMetrics(
        prefix: "trove",
        bottomY: 0.9385,
        rimY: 0.5284,
        openingLeft: 0.0884,
        openingRight: 0.9116,
        lidHinge: UnitPoint(x: 0.0561, y: 0.6416),
        lidRise: 0.3002,
        cardPeakY: 0.3614,
        cardWidth: 0.247
    )
    static let deckBox = RenderedArtworkMetrics(
        prefix: "deckbox",
        bottomY: 0.965,
        rimY: 0.4253,
        openingLeft: 0.2229,
        openingRight: 0.7771,
        lidHinge: UnitPoint(x: 0.1823, y: 0.5825),
        lidRise: 0.3133,
        cardPeakY: 0.2893,
        cardWidth: 0.2328
    )
    static let storageBox = RenderedArtworkMetrics(
        prefix: "storagebox",
        bottomY: 0.965,
        rimY: 0.5385,
        openingLeft: 0.063,
        openingRight: 0.937,
        lidHinge: UnitPoint(x: 0.0443, y: 0.6496),
        lidRise: 0.2751,
        cardPeakY: 0.3945,
        cardWidth: 0.1573
    )
    static let bulkBin = RenderedArtworkMetrics(
        prefix: "bulkbin",
        bottomY: 0.9528,
        rimY: 0.5313,
        openingLeft: 0.0593,
        openingRight: 0.9407,
        cardWidth: 0.2115
    )
    static let other = RenderedArtworkMetrics(
        prefix: "otherbox",
        bottomY: 0.965,
        rimY: 0.4995,
        openingLeft: 0.1729,
        openingRight: 0.8271,
        lidHinge: UnitPoint(x: 0.1406, y: 0.6172),
        lidRise: 0.3339,
        cardPeakY: 0.3033,
        cardWidth: 0.1963
    )
    static let binderCover = RenderedArtworkMetrics(
        prefix: "bindercover",
        bottomY: 0.9961
    )
    static let binderSpine = RenderedArtworkMetrics(
        prefix: "binderspine",
        bottomY: 0.989,
        label: CGRect(x: 0.191, y: 0.1968, width: 0.5731, height: 0.489)
    )

    // Where the binder cover's ornaments sit on the cover (fractions of its size).
    static let coverEmblem = CGRect(x: 0.4286, y: 0.5057, width: 0.2921, height: 0.2271)
    static let coverPlate = CGRect(x: 0.3132, y: 0.1721, width: 0.522, height: 0.1593)
}
