#!/usr/bin/env python3
"""Install rendered storage-art layers into the app.

    python3 Scripts/storage_art/install_assets.py <render_dir>

* Every `<name>.png` becomes `Assets.xcassets/StorageArt/<name>.imageset`. The
  folder is regenerated from scratch, so renamed or dropped layers don't linger.
* Masks only need their alpha, so they're stored as grayscale + alpha.
* The binder cover's ornaments (plate, emblem) are cropped to their content and
  their place on the cover recorded, so the app can position them unstretched.
* `<kind>_metrics.json` files become
  `Components/Storage/RenderedArtworkMetrics+Generated.swift`.
"""

import json
import shutil
import sys
from pathlib import Path

from PIL import Image

APP = Path(__file__).resolve().parents[2] / "Inkwell Keeper"
CATALOG = APP / "Assets.xcassets" / "StorageArt"
SWIFT_OUT = APP / "Components" / "Storage" / "RenderedArtworkMetrics+Generated.swift"
ORNAMENTS = {"bindercover_plate": "coverPlate", "bindercover_emblem": "coverEmblem"}
# Render kind → StorageKind-facing static name.
KIND_NAMES = {
    "binder": "binder", "trove": "trove", "deckbox": "deckBox",
    "storagebox": "storageBox", "bulkbin": "bulkBin", "otherbox": "other", "bindercover": "binderCover",
    "binderspine": "binderSpine",
}


def write_json(path, payload):
    path.write_text(json.dumps(payload, indent=2) + "\n")


def swift_number(value):
    return f"{value:.4f}".rstrip("0").rstrip(".") if value else "0"


def main():
    render_dir = Path(sys.argv[1])
    shutil.rmtree(CATALOG, ignore_errors=True)
    CATALOG.mkdir(parents=True)
    write_json(CATALOG / "Contents.json", {"info": {"author": "xcode", "version": 1}})

    ornament_rects = {}
    total = 0
    for source in sorted(render_dir.glob("*.png")):
        image = Image.open(source)
        if source.stem.endswith("_mask"):
            alpha = image.convert("RGBA").getchannel("A")
            image = Image.merge("LA", (Image.new("L", image.size, 255), alpha))
        elif source.stem in ORNAMENTS:
            left, top, right, bottom = image.getchannel("A").getbbox()
            width, height = image.size
            ornament_rects[ORNAMENTS[source.stem]] = (left / width, top / height, (right - left) / width, (bottom - top) / height)
            image = image.crop((left, top, right, bottom))
        imageset = CATALOG / f"{source.stem}.imageset"
        imageset.mkdir()
        image.save(imageset / source.name, optimize=True)
        contents = {
            "images": [{"filename": source.name, "idiom": "universal"}],
            "info": {"author": "xcode", "version": 1},
        }
        if not source.stem.endswith("_mask"):
            # Soft, photographic renders: lossy storage is invisible and far smaller.
            contents["properties"] = {"compression-type": "lossy"}
        write_json(imageset / "Contents.json", contents)
        total += (imageset / source.name).stat().st_size
    print(f"installed {len(list(CATALOG.glob('*.imageset')))} images, {total // 1024} KB")

    lines = [
        "//",
        "//  RenderedArtworkMetrics+Generated.swift",
        "//  Inkwell Keeper",
        "//",
        "//  Generated by Scripts/storage_art/install_assets.py from the Blender renders.",
        "//  Do not edit by hand — re-run the render and install scripts instead.",
        "//",
        "",
        "import SwiftUI",
        "",
        "extension RenderedArtworkMetrics {",
    ]
    for kind, name in KIND_NAMES.items():
        metrics = json.loads((render_dir / f"{kind}_metrics.json").read_text())
        args = [f'prefix: "{kind}"', f"bottomY: {swift_number(metrics['bottomY'])}"]
        if "rimY" in metrics:
            args += [
                f"rimY: {swift_number(metrics['rimY'])}",
                f"openingLeft: {swift_number(metrics['openingLeft'])}",
                f"openingRight: {swift_number(metrics['openingRight'])}",
            ]
        if "lidHingeX" in metrics:
            args += [
                f"lidHinge: UnitPoint(x: {swift_number(metrics['lidHingeX'])}, y: {swift_number(metrics['lidHingeY'])})",
                f"lidRise: {swift_number(metrics['lidRise'])}",
                f"cardPeakY: {swift_number(metrics['cardPeakY'])}",
            ]
        if "cardWidth" in metrics:
            args.append(f"cardWidth: {swift_number(metrics['cardWidth'])}")
        if "labelX" in metrics:
            rect = ", ".join(f"{key}: {swift_number(metrics['label' + key.capitalize()])}" for key in ("x", "y", "width", "height"))
            args.append(f"label: CGRect({rect})")
        lines.append(f"    static let {name} = RenderedArtworkMetrics(")
        lines += [f"        {arg}," for arg in args[:-1]]
        lines += [f"        {args[-1]}", "    )"]
    lines.append("")
    lines.append("    // Where the binder cover's ornaments sit on the cover (fractions of its size).")
    for name, (x, y, w, h) in sorted(ornament_rects.items()):
        lines.append(f"    static let {name} = CGRect(x: {swift_number(x)}, y: {swift_number(y)}, width: {swift_number(w)}, height: {swift_number(h)})")
    lines += ["}", ""]
    SWIFT_OUT.write_text("\n".join(lines))
    print(f"wrote {SWIFT_OUT.name}")


main()
